/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Fri Jan 30 13:47:10 2026


#ifndef XHANDCONTROLBOARD_PARAMSPARSER_H
#define XHANDCONTROLBOARD_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class xHandControlBoard.
*
* These are the used parameters:
* | Group name | Parameter name  | Type           | Units | Default Value                                                           | Required | Description                                               | Notes                                                    |
* |:----------:|:---------------:|:--------------:|:-----:|:-----------------------------------------------------------------------:|:--------:|:---------------------------------------------------------:|:--------------------------------------------------------:|
* | -          | connection_type | string         | -     | EtherCAT                                                                | 1        | Specify the connection type                               | Can be either \"RS485\" (USB) or \"EtherCAT\" (ethernet) |
* | RS485      | port            | string         | -     | /dev/ttyUSB0                                                            | 0        | Specify the port to use for the serial connection         | Necessary only if using \"RS485\"                        |
* | RS485      | baudrate        | int            | -     | 3000000                                                                 | 0        | Specify the baudrate for the serial connection            | Necessary only if using \"RS485\"                        |
* | ETHERCAT   | eth_ifname      | string         | -     | -                                                                       | 0        | Specify the interface name for the ethercat connection    | Necessary only if using \"EtherCAT\"                     |
* | PID        | kp              | int            | -     | 225                                                                     | 0        | Finger motors P gain                                      | -                                                        |
* | PID        | ki              | int            | -     | 0                                                                       | 0        | Finger motors I gain                                      | -                                                        |
* | PID        | kd              | int            | -     | 12000                                                                   | 0        | Finger motors D gain                                      | -                                                        |
* | TORQUE     | tor_max         | int            | -     | 350                                                                     | 0        | Note: 350 is the value from their ethercat_test           | -                                                        |
* | MODE       | mode            | int            | -     | 3                                                                       | 0        | Powerless = 0; Powerfull = 3; Check the manual for others | -                                                        |
* | LIMITS     | jntPosMin       | vector<double> | deg   | (0.0 -60.0 -10.0 -10.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0)                 | 0        | -                                                         | -                                                        |
* | LIMITS     | jntPosMax       | vector<double> | deg   | (105.0 90.0 105.0 10.0 110.0 110.0 110.0 110.0 110.0 110.0 110.0 110.0) | 0        | -                                                         | -                                                        |
* | GENERAL    | AxisName        | vector<string> | -     | (a a a a a a a a a a a a)                                               | 0        | -                                                         | -                                                        |
* | GENERAL    | AxisType        | vector<string> | -     | (a a a a a a a a a a a a)                                               | 0        | -                                                         | -                                                        |
* | GENERAL    | AxisMap         | vector<int>    | -     | (0 0 0 0 0 0 0 0 0 0 0 0)                                               | 0        | -                                                         | -                                                        |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device xHandControlBoard --connection_type EtherCAT --RS485::port /dev/ttyUSB0 --RS485::baudrate 3000000 --ETHERCAT::eth_ifname <optional_value> --PID::kp 225 --PID::ki 0 --PID::kd 12000 --TORQUE::tor_max 350 --MODE::mode 3 --LIMITS::jntPosMin \" (0.0 -60.0 -10.0 -10.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0) \" --LIMITS::jntPosMax \" (105.0 90.0 105.0 10.0 110.0 110.0 110.0 110.0 110.0 110.0 110.0 110.0) \" --GENERAL::AxisName \" (a a a a a a a a a a a a) \" --GENERAL::AxisType \" (a a a a a a a a a a a a) \" --GENERAL::AxisMap \" (0 0 0 0 0 0 0 0 0 0 0 0) \"
* \endcode
*
* \code{.unparsed}
* yarpdev --device xHandControlBoard --connection_type EtherCAT
* \endcode
*
*/

class xHandControlBoard_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    xHandControlBoard_ParamsParser();
    ~xHandControlBoard_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"xHandControlBoard"};
    const std::string m_device_name = {"xHandControlBoard"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_connection_type_defaultValue = {"EtherCAT"};
    const std::string m_RS485_port_defaultValue = {"/dev/ttyUSB0"};
    const std::string m_RS485_baudrate_defaultValue = {"3000000"};
    const std::string m_ETHERCAT_eth_ifname_defaultValue = {""};
    const std::string m_PID_kp_defaultValue = {"225"};
    const std::string m_PID_ki_defaultValue = {"0"};
    const std::string m_PID_kd_defaultValue = {"12000"};
    const std::string m_TORQUE_tor_max_defaultValue = {"350"};
    const std::string m_MODE_mode_defaultValue = {"3"};
    const std::string m_LIMITS_jntPosMin_defaultValue = {"(0.0 -60.0 -10.0 -10.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0)"};
    const std::string m_LIMITS_jntPosMax_defaultValue = {"(105.0 90.0 105.0 10.0 110.0 110.0 110.0 110.0 110.0 110.0 110.0 110.0)"};
    const std::string m_GENERAL_AxisName_defaultValue = {"(a a a a a a a a a a a a)"};
    const std::string m_GENERAL_AxisType_defaultValue = {"(a a a a a a a a a a a a)"};
    const std::string m_GENERAL_AxisMap_defaultValue = {"(0 0 0 0 0 0 0 0 0 0 0 0)"};

    std::string m_connection_type = {"EtherCAT"};
    std::string m_RS485_port = {"/dev/ttyUSB0"};
    int m_RS485_baudrate = {3000000};
    std::string m_ETHERCAT_eth_ifname = {}; //This default value of this string is an empty string. It is highly recommended to provide a suggested value also for optional string parameters.
    int m_PID_kp = {225};
    int m_PID_ki = {0};
    int m_PID_kd = {12000};
    int m_TORQUE_tor_max = {350};
    int m_MODE_mode = {3};
    std::vector<double> m_LIMITS_jntPosMin = { }; //Default values for lists are managed in the class constructor. It is highly recommended to provide a suggested value also for optional string parameters.
    std::vector<double> m_LIMITS_jntPosMax = { }; //Default values for lists are managed in the class constructor. It is highly recommended to provide a suggested value also for optional string parameters.
    std::vector<std::string> m_GENERAL_AxisName = { }; //Default values for lists are managed in the class constructor. It is highly recommended to provide a suggested value also for optional string parameters.
    std::vector<std::string> m_GENERAL_AxisType = { }; //Default values for lists are managed in the class constructor. It is highly recommended to provide a suggested value also for optional string parameters.
    std::vector<int> m_GENERAL_AxisMap = { }; //Default values for lists are managed in the class constructor. It is highly recommended to provide a suggested value also for optional string parameters.

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
