/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon Nov 10 10:53:48 2025


#include "xHandControlBoard_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(xHandControlBoardParamsCOMPONENT, "yarp.device.xHandControlBoard")
}


xHandControlBoard_ParamsParser::xHandControlBoard_ParamsParser()
{
}


std::vector<std::string> xHandControlBoard_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("connection_type");
    params.push_back("serial_port");
    params.push_back("baudrate");
    params.push_back("eth_ifname");
    return params;
}


bool      xHandControlBoard_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(xHandControlBoardParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter connection_type
    {
        if (config.check("connection_type"))
        {
            m_connection_type = config.find("connection_type").asString();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'connection_type' using value:" << m_connection_type;
        }
        else
        {
            yCError(xHandControlBoardParamsCOMPONENT) << "Mandatory parameter 'connection_type' not found!";
            yCError(xHandControlBoardParamsCOMPONENT) << "Description of the parameter: Specify the connection type";
            return false;
        }
        prop_check.unput("connection_type");
    }

    //Parser of parameter serial_port
    {
        if (config.check("serial_port"))
        {
            m_serial_port = config.find("serial_port").asString();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'serial_port' using value:" << m_serial_port;
        }
        else
        {
            yCError(xHandControlBoardParamsCOMPONENT) << "Mandatory parameter 'serial_port' not found!";
            yCError(xHandControlBoardParamsCOMPONENT) << "Description of the parameter: Specify the port to use for the serial connection";
            return false;
        }
        prop_check.unput("serial_port");
    }

    //Parser of parameter baudrate
    {
        if (config.check("baudrate"))
        {
            m_baudrate = config.find("baudrate").asInt64();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'baudrate' using value:" << m_baudrate;
        }
        else
        {
            yCError(xHandControlBoardParamsCOMPONENT) << "Mandatory parameter 'baudrate' not found!";
            yCError(xHandControlBoardParamsCOMPONENT) << "Description of the parameter: Specify the baudrate for the serial connection";
            return false;
        }
        prop_check.unput("baudrate");
    }

    //Parser of parameter eth_ifname
    {
        if (config.check("eth_ifname"))
        {
            m_eth_ifname = config.find("eth_ifname").asString();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'eth_ifname' using value:" << m_eth_ifname;
        }
        else
        {
            yCError(xHandControlBoardParamsCOMPONENT) << "Mandatory parameter 'eth_ifname' not found!";
            yCError(xHandControlBoardParamsCOMPONENT) << "Description of the parameter: Specify the interface name for the ethercat connection";
            return false;
        }
        prop_check.unput("eth_ifname");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(xHandControlBoardParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(xHandControlBoardParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      xHandControlBoard_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: xHandControlBoard\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'connection_type': Specify the connection type\n");
    doc = doc + std::string("'serial_port': Specify the port to use for the serial connection\n");
    doc = doc + std::string("'baudrate': Specify the baudrate for the serial connection\n");
    doc = doc + std::string("'eth_ifname': Specify the interface name for the ethercat connection\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device xHandControlBoard --connection_type <mandatory_value> --serial_port <mandatory_value> --baudrate <mandatory_value> --eth_ifname <mandatory_value>\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device xHandControlBoard --connection_type <mandatory_value> --serial_port <mandatory_value> --baudrate <mandatory_value> --eth_ifname <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
