/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Wed Feb  4 14:27:58 2026


#include "xHandControlBoard_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(xHandControlBoardParamsCOMPONENT, "yarp.device.xHandControlBoard")
}


xHandControlBoard_ParamsParser::xHandControlBoard_ParamsParser()
{
    //Default value of parameterLIMITS_jntPosMin
    {
        m_LIMITS_jntPosMin.clear();
        yarp::os::Value tempVal;
        tempVal.fromString(m_LIMITS_jntPosMin_defaultValue.c_str());
        yarp::os::Bottle* tempBot = tempVal.asList();
        if (tempBot && tempBot->size()!=0)
        {
            for (size_t i=0; i<tempBot->size(); i++)
            {
                m_LIMITS_jntPosMin.push_back(tempBot->get(i).asFloat64());
            }
        }
        else
        {
             yError() <<"parameter 'LIMITS_jntPosMin' is not a properly formatted bottle";
        }
    }

    //Default value of parameterLIMITS_jntPosMax
    {
        m_LIMITS_jntPosMax.clear();
        yarp::os::Value tempVal;
        tempVal.fromString(m_LIMITS_jntPosMax_defaultValue.c_str());
        yarp::os::Bottle* tempBot = tempVal.asList();
        if (tempBot && tempBot->size()!=0)
        {
            for (size_t i=0; i<tempBot->size(); i++)
            {
                m_LIMITS_jntPosMax.push_back(tempBot->get(i).asFloat64());
            }
        }
        else
        {
             yError() <<"parameter 'LIMITS_jntPosMax' is not a properly formatted bottle";
        }
    }

    //Default value of parameterLIMITS_jntVelMin
    {
        m_LIMITS_jntVelMin.clear();
        yarp::os::Value tempVal;
        tempVal.fromString(m_LIMITS_jntVelMin_defaultValue.c_str());
        yarp::os::Bottle* tempBot = tempVal.asList();
        if (tempBot && tempBot->size()!=0)
        {
            for (size_t i=0; i<tempBot->size(); i++)
            {
                m_LIMITS_jntVelMin.push_back(tempBot->get(i).asFloat64());
            }
        }
        else
        {
             yError() <<"parameter 'LIMITS_jntVelMin' is not a properly formatted bottle";
        }
    }

    //Default value of parameterLIMITS_jntVelMax
    {
        m_LIMITS_jntVelMax.clear();
        yarp::os::Value tempVal;
        tempVal.fromString(m_LIMITS_jntVelMax_defaultValue.c_str());
        yarp::os::Bottle* tempBot = tempVal.asList();
        if (tempBot && tempBot->size()!=0)
        {
            for (size_t i=0; i<tempBot->size(); i++)
            {
                m_LIMITS_jntVelMax.push_back(tempBot->get(i).asFloat64());
            }
        }
        else
        {
             yError() <<"parameter 'LIMITS_jntVelMax' is not a properly formatted bottle";
        }
    }

    //Default value of parameterGENERAL_AxisName
    {
        m_GENERAL_AxisName.clear();
        yarp::os::Value tempVal;
        tempVal.fromString(m_GENERAL_AxisName_defaultValue.c_str());
        yarp::os::Bottle* tempBot = tempVal.asList();
        if (tempBot && tempBot->size()!=0)
        {
            for (size_t i=0; i<tempBot->size(); i++)
            {
                m_GENERAL_AxisName.push_back(tempBot->get(i).asString());
            }
        }
        else
        {
             yError() <<"parameter 'GENERAL_AxisName' is not a properly formatted bottle";
        }
    }

    //Default value of parameterGENERAL_AxisType
    {
        m_GENERAL_AxisType.clear();
        yarp::os::Value tempVal;
        tempVal.fromString(m_GENERAL_AxisType_defaultValue.c_str());
        yarp::os::Bottle* tempBot = tempVal.asList();
        if (tempBot && tempBot->size()!=0)
        {
            for (size_t i=0; i<tempBot->size(); i++)
            {
                m_GENERAL_AxisType.push_back(tempBot->get(i).asString());
            }
        }
        else
        {
             yError() <<"parameter 'GENERAL_AxisType' is not a properly formatted bottle";
        }
    }

    //Default value of parameterGENERAL_AxisMap
    {
        m_GENERAL_AxisMap.clear();
        yarp::os::Value tempVal;
        tempVal.fromString(m_GENERAL_AxisMap_defaultValue.c_str());
        yarp::os::Bottle* tempBot = tempVal.asList();
        if (tempBot && tempBot->size()!=0)
        {
            for (size_t i=0; i<tempBot->size(); i++)
            {
                m_GENERAL_AxisMap.push_back(tempBot->get(i).asInt64());
            }
        }
        else
        {
             yError() <<"parameter 'GENERAL_AxisMap' is not a properly formatted bottle";
        }
    }

}


std::vector<std::string> xHandControlBoard_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("connection_type");
    params.push_back("RS485::port");
    params.push_back("RS485::baudrate");
    params.push_back("ETHERCAT::eth_ifname");
    params.push_back("PID::kp");
    params.push_back("PID::ki");
    params.push_back("PID::kd");
    params.push_back("TORQUE::tor_max");
    params.push_back("MODE::mode");
    params.push_back("LIMITS::jntPosMin");
    params.push_back("LIMITS::jntPosMax");
    params.push_back("LIMITS::jntVelMin");
    params.push_back("LIMITS::jntVelMax");
    params.push_back("GENERAL::AxisName");
    params.push_back("GENERAL::AxisType");
    params.push_back("GENERAL::AxisMap");
    return params;
}


bool xHandControlBoard_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="connection_type")
    {
        paramValue = m_connection_type;
        return true;
    }
    if (paramName =="RS485::port")
    {
        paramValue = m_RS485_port;
        return true;
    }
    if (paramName =="RS485::baudrate")
    {
        paramValue = std::to_string(m_RS485_baudrate);
        return true;
    }
    if (paramName =="ETHERCAT::eth_ifname")
    {
        paramValue = m_ETHERCAT_eth_ifname;
        return true;
    }
    if (paramName =="PID::kp")
    {
        paramValue = std::to_string(m_PID_kp);
        return true;
    }
    if (paramName =="PID::ki")
    {
        paramValue = std::to_string(m_PID_ki);
        return true;
    }
    if (paramName =="PID::kd")
    {
        paramValue = std::to_string(m_PID_kd);
        return true;
    }
    if (paramName =="TORQUE::tor_max")
    {
        paramValue = std::to_string(m_TORQUE_tor_max);
        return true;
    }
    if (paramName =="MODE::mode")
    {
        paramValue = std::to_string(m_MODE_mode);
        return true;
    }
    if (paramName =="LIMITS::jntPosMin")
    {
        return false;
    }
    if (paramName =="LIMITS::jntPosMax")
    {
        return false;
    }
    if (paramName =="LIMITS::jntVelMin")
    {
        return false;
    }
    if (paramName =="LIMITS::jntVelMax")
    {
        return false;
    }
    if (paramName =="GENERAL::AxisName")
    {
        return false;
    }
    if (paramName =="GENERAL::AxisType")
    {
        return false;
    }
    if (paramName =="GENERAL::AxisMap")
    {
        return false;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string xHandControlBoard_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      xHandControlBoard_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(xHandControlBoardParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter connection_type
    {
        if (config.check("connection_type"))
        {
            m_connection_type = config.find("connection_type").asString();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'connection_type' using value:" << m_connection_type;
        }
        else
        {
            yCError(xHandControlBoardParamsCOMPONENT) << "Mandatory parameter 'connection_type' not found!";
            yCError(xHandControlBoardParamsCOMPONENT) << "Description of the parameter: Specify the connection type";
            return false;
        }
        prop_check.unput("connection_type");
    }

    //Parser of parameter RS485::port
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("RS485");
        if (sectionp.check("port"))
        {
            m_RS485_port = sectionp.find("port").asString();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'RS485::port' using value:" << m_RS485_port;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'RS485::port' using DEFAULT value:" << m_RS485_port;
        }
        prop_check.unput("RS485::port");
    }

    //Parser of parameter RS485::baudrate
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("RS485");
        if (sectionp.check("baudrate"))
        {
            m_RS485_baudrate = sectionp.find("baudrate").asInt64();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'RS485::baudrate' using value:" << m_RS485_baudrate;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'RS485::baudrate' using DEFAULT value:" << m_RS485_baudrate;
        }
        prop_check.unput("RS485::baudrate");
    }

    //Parser of parameter ETHERCAT::eth_ifname
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("ETHERCAT");
        if (sectionp.check("eth_ifname"))
        {
            m_ETHERCAT_eth_ifname = sectionp.find("eth_ifname").asString();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'ETHERCAT::eth_ifname' using value:" << m_ETHERCAT_eth_ifname;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'ETHERCAT::eth_ifname' using DEFAULT value:" << m_ETHERCAT_eth_ifname;
        }
        prop_check.unput("ETHERCAT::eth_ifname");
    }

    //Parser of parameter PID::kp
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("PID");
        if (sectionp.check("kp"))
        {
            m_PID_kp = sectionp.find("kp").asInt64();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'PID::kp' using value:" << m_PID_kp;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'PID::kp' using DEFAULT value:" << m_PID_kp;
        }
        prop_check.unput("PID::kp");
    }

    //Parser of parameter PID::ki
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("PID");
        if (sectionp.check("ki"))
        {
            m_PID_ki = sectionp.find("ki").asInt64();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'PID::ki' using value:" << m_PID_ki;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'PID::ki' using DEFAULT value:" << m_PID_ki;
        }
        prop_check.unput("PID::ki");
    }

    //Parser of parameter PID::kd
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("PID");
        if (sectionp.check("kd"))
        {
            m_PID_kd = sectionp.find("kd").asInt64();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'PID::kd' using value:" << m_PID_kd;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'PID::kd' using DEFAULT value:" << m_PID_kd;
        }
        prop_check.unput("PID::kd");
    }

    //Parser of parameter TORQUE::tor_max
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("TORQUE");
        if (sectionp.check("tor_max"))
        {
            m_TORQUE_tor_max = sectionp.find("tor_max").asInt64();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'TORQUE::tor_max' using value:" << m_TORQUE_tor_max;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'TORQUE::tor_max' using DEFAULT value:" << m_TORQUE_tor_max;
        }
        prop_check.unput("TORQUE::tor_max");
    }

    //Parser of parameter MODE::mode
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("MODE");
        if (sectionp.check("mode"))
        {
            m_MODE_mode = sectionp.find("mode").asInt64();
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'MODE::mode' using value:" << m_MODE_mode;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'MODE::mode' using DEFAULT value:" << m_MODE_mode;
        }
        prop_check.unput("MODE::mode");
    }

    //Parser of parameter LIMITS::jntPosMin
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("LIMITS");
        if (sectionp.check("jntPosMin"))
        {
            {
                m_LIMITS_jntPosMin.clear();
                yarp::os::Bottle* tempBot = sectionp.find("jntPosMin").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_LIMITS_jntPosMin.push_back(tempBot->get(i).asFloat64());
                    }
                }
                else
                {
                     yCError(xHandControlBoardParamsCOMPONENT) <<"parameter 'LIMITS_jntPosMin' is not a properly formatted bottle";
                }
            }
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'LIMITS::jntPosMin' using value:" << m_LIMITS_jntPosMin;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'LIMITS::jntPosMin' using DEFAULT value:" << m_LIMITS_jntPosMin;
        }
        prop_check.unput("LIMITS::jntPosMin");
    }

    //Parser of parameter LIMITS::jntPosMax
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("LIMITS");
        if (sectionp.check("jntPosMax"))
        {
            {
                m_LIMITS_jntPosMax.clear();
                yarp::os::Bottle* tempBot = sectionp.find("jntPosMax").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_LIMITS_jntPosMax.push_back(tempBot->get(i).asFloat64());
                    }
                }
                else
                {
                     yCError(xHandControlBoardParamsCOMPONENT) <<"parameter 'LIMITS_jntPosMax' is not a properly formatted bottle";
                }
            }
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'LIMITS::jntPosMax' using value:" << m_LIMITS_jntPosMax;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'LIMITS::jntPosMax' using DEFAULT value:" << m_LIMITS_jntPosMax;
        }
        prop_check.unput("LIMITS::jntPosMax");
    }

    //Parser of parameter LIMITS::jntVelMin
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("LIMITS");
        if (sectionp.check("jntVelMin"))
        {
            {
                m_LIMITS_jntVelMin.clear();
                yarp::os::Bottle* tempBot = sectionp.find("jntVelMin").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_LIMITS_jntVelMin.push_back(tempBot->get(i).asFloat64());
                    }
                }
                else
                {
                     yCError(xHandControlBoardParamsCOMPONENT) <<"parameter 'LIMITS_jntVelMin' is not a properly formatted bottle";
                }
            }
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'LIMITS::jntVelMin' using value:" << m_LIMITS_jntVelMin;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'LIMITS::jntVelMin' using DEFAULT value:" << m_LIMITS_jntVelMin;
        }
        prop_check.unput("LIMITS::jntVelMin");
    }

    //Parser of parameter LIMITS::jntVelMax
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("LIMITS");
        if (sectionp.check("jntVelMax"))
        {
            {
                m_LIMITS_jntVelMax.clear();
                yarp::os::Bottle* tempBot = sectionp.find("jntVelMax").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_LIMITS_jntVelMax.push_back(tempBot->get(i).asFloat64());
                    }
                }
                else
                {
                     yCError(xHandControlBoardParamsCOMPONENT) <<"parameter 'LIMITS_jntVelMax' is not a properly formatted bottle";
                }
            }
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'LIMITS::jntVelMax' using value:" << m_LIMITS_jntVelMax;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'LIMITS::jntVelMax' using DEFAULT value:" << m_LIMITS_jntVelMax;
        }
        prop_check.unput("LIMITS::jntVelMax");
    }

    //Parser of parameter GENERAL::AxisName
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("GENERAL");
        if (sectionp.check("AxisName"))
        {
            {
                m_GENERAL_AxisName.clear();
                yarp::os::Bottle* tempBot = sectionp.find("AxisName").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_GENERAL_AxisName.push_back(tempBot->get(i).asString());
                    }
                }
                else
                {
                     yCError(xHandControlBoardParamsCOMPONENT) <<"parameter 'GENERAL_AxisName' is not a properly formatted bottle";
                }
            }
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'GENERAL::AxisName' using value:" << m_GENERAL_AxisName;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'GENERAL::AxisName' using DEFAULT value:" << m_GENERAL_AxisName;
        }
        prop_check.unput("GENERAL::AxisName");
    }

    //Parser of parameter GENERAL::AxisType
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("GENERAL");
        if (sectionp.check("AxisType"))
        {
            {
                m_GENERAL_AxisType.clear();
                yarp::os::Bottle* tempBot = sectionp.find("AxisType").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_GENERAL_AxisType.push_back(tempBot->get(i).asString());
                    }
                }
                else
                {
                     yCError(xHandControlBoardParamsCOMPONENT) <<"parameter 'GENERAL_AxisType' is not a properly formatted bottle";
                }
            }
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'GENERAL::AxisType' using value:" << m_GENERAL_AxisType;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'GENERAL::AxisType' using DEFAULT value:" << m_GENERAL_AxisType;
        }
        prop_check.unput("GENERAL::AxisType");
    }

    //Parser of parameter GENERAL::AxisMap
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("GENERAL");
        if (sectionp.check("AxisMap"))
        {
            {
                m_GENERAL_AxisMap.clear();
                yarp::os::Bottle* tempBot = sectionp.find("AxisMap").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_GENERAL_AxisMap.push_back(tempBot->get(i).asInt64());
                    }
                }
                else
                {
                     yCError(xHandControlBoardParamsCOMPONENT) <<"parameter 'GENERAL_AxisMap' is not a properly formatted bottle";
                }
            }
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'GENERAL::AxisMap' using value:" << m_GENERAL_AxisMap;
        }
        else
        {
            yCInfo(xHandControlBoardParamsCOMPONENT) << "Parameter 'GENERAL::AxisMap' using DEFAULT value:" << m_GENERAL_AxisMap;
        }
        prop_check.unput("GENERAL::AxisMap");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(xHandControlBoardParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(xHandControlBoardParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      xHandControlBoard_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: xHandControlBoard\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'connection_type': Specify the connection type\n");
    doc = doc + std::string("'RS485::port': Specify the port to use for the serial connection\n");
    doc = doc + std::string("'RS485::baudrate': Specify the baudrate for the serial connection\n");
    doc = doc + std::string("'ETHERCAT::eth_ifname': Specify the interface name for the ethercat connection\n");
    doc = doc + std::string("'PID::kp': Finger motors P gain\n");
    doc = doc + std::string("'PID::ki': Finger motors I gain\n");
    doc = doc + std::string("'PID::kd': Finger motors D gain\n");
    doc = doc + std::string("'TORQUE::tor_max': Note: 350 is the value from their ethercat_test\n");
    doc = doc + std::string("'MODE::mode': Powerless = 0; Powerfull = 3; Check the manual for others\n");
    doc = doc + std::string("'LIMITS::jntPosMin': \n");
    doc = doc + std::string("'LIMITS::jntPosMax': \n");
    doc = doc + std::string("'LIMITS::jntVelMin': \n");
    doc = doc + std::string("'LIMITS::jntVelMax': \n");
    doc = doc + std::string("'GENERAL::AxisName': \n");
    doc = doc + std::string("'GENERAL::AxisType': \n");
    doc = doc + std::string("'GENERAL::AxisMap': \n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device xHandControlBoard --connection_type EtherCAT --RS485::port /dev/ttyUSB0 --RS485::baudrate 3000000 --ETHERCAT::eth_ifname <optional_value> --PID::kp 225 --PID::ki 0 --PID::kd 12000 --TORQUE::tor_max 350 --MODE::mode 3 --LIMITS::jntPosMin \" (0.0 -60.0 -10.0 -10.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0) \" --LIMITS::jntPosMax \" (105.0 90.0 105.0 10.0 110.0 110.0 110.0 110.0 110.0 110.0 110.0 110.0) \" --LIMITS::jntVelMin \" (0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0) \" --LIMITS::jntVelMax \" (100.0 100.0 100.0 100.0 100.0 100.0 100.0 100.0 100.0 100.0 100.0 100.0) \" --GENERAL::AxisName \" (a a a a a a a a a a a a) \" --GENERAL::AxisType \" (a a a a a a a a a a a a) \" --GENERAL::AxisMap \" (0 0 0 0 0 0 0 0 0 0 0 0) \"\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device xHandControlBoard --connection_type EtherCAT\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
