/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Fri Nov  7 17:48:26 2025


#ifndef XHANDCONTROLBOARD_PARAMSPARSER_H
#define XHANDCONTROLBOARD_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class xHandControlBoard.
*
* These are the used parameters:
* | Group name | Parameter name  | Type   | Units | Default Value | Required | Description                                       | Notes                                    |
* |:----------:|:---------------:|:------:|:-----:|:-------------:|:--------:|:-------------------------------------------------:|:----------------------------------------:|
* | -          | connection_type | string | -     | -             | 1        | Specify the connection type                       | Can be either \"serial\" or \"ethercat\" |
* | -          | serial_port     | string | -     | -             | 1        | Specify the port to use for the serial connection | Necessary only if using \"serial\"       |
* | -          | baudrate        | int    | -     | -             | 1        | Specify the baudrate for the serial connection    | Necessary only if using \"serial\"       |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device xHandControlBoard --connection_type <mandatory_value> --serial_port <mandatory_value> --baudrate <mandatory_value>
* \endcode
*
* \code{.unparsed}
* yarpdev --device xHandControlBoard --connection_type <mandatory_value> --serial_port <mandatory_value> --baudrate <mandatory_value>
* \endcode
*
*/

class xHandControlBoard_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    xHandControlBoard_ParamsParser();
    ~xHandControlBoard_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"xHandControlBoard"};
    const std::string m_device_name = {"xHandControlBoard"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 1;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    const std::string m_connection_type_defaultValue = {""};
    const std::string m_serial_port_defaultValue = {""};
    const std::string m_baudrate_defaultValue = {""};

    std::string m_connection_type = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::string m_serial_port = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    int m_baudrate = {0}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
};

#endif
